FROM node:20-alpine AS deps
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl && npm install -g pnpm@9.1.0
COPY .npmrc ./
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/
RUN pnpm install --frozen-lockfile

FROM node:20-alpine AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl && npm install -g pnpm@9.1.0
COPY --from=deps /app/node_modules /app/node_modules
COPY . .
RUN npx prisma generate --schema prisma/schema.prisma
RUN pnpm --filter @gubernajur/api build

FROM node:20-alpine AS runner
WORKDIR /app/apps/api
ENV NODE_ENV=production
RUN apk add --no-cache openssl && \
    addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 gubernajur
COPY --from=builder --chown=gubernajur:nodejs /app/apps/api/dist ./dist
COPY --from=builder --chown=gubernajur:nodejs /app/apps/api/package.json ./package.json
COPY --from=builder --chown=gubernajur:nodejs /app/node_modules /app/node_modules
COPY --from=builder --chown=gubernajur:nodejs /app/prisma /app/prisma
USER gubernajur
EXPOSE 3001
CMD ["node", "dist/main"]
